### ISSUE TITLE
Nuove attività

### ISSUE THREAD

**Issue by Verticalsrl** [Verticalsrl/progettoPNI_2#12]
- [x] aggiungere i seguenti campi sotto il layer tratta

- [x] ripr_contestuale -->	bool 
- [x] ripr_cls --> bool   
- [x] prop_privata --> bool 
- [x] sottofondo_bituminoso --> bool 
- [x] mtubi_tipologia --> varchar 100
- [x] disfacimento_tipo -->varchar	100
- [x] georadar	 -->bool
- [x] microt_diam_min80 -->	varchar 100
- [x] autoestinguente	 -->bool 
- [x] mtubi_calza	 -->bool	

sotto layer pozzetto

- [x] giunto_3vie	 -->varchar 100
- [x] campo "chiusino" --> bool

Tabella user_log

- [x] url --> cher 500

- [x] Fare un update tra la tabella elenco_prezzi_roma e elenco_prezzi_roma_update la chiave è art i valori da aggiornare sono "prezzo" mi giri poi scrivi qui la query

- [x] Caricare su Qgis template aeb la tabella user_log_map e elenco_prezzi_layer, quest'ultima è da generare così sotto ogni schema:

CREATE TABLE "public"."olbia_elenco_prezzi_layers" (
  "idprezzo" int8 NOT NULL,
  "laygidd" int8 NOT NULL,
  "layname" varchar(200) COLLATE "pg_catalog"."default" NOT NULL,
  "insDate" timestamp(0) NOT NULL DEFAULT now(),
  "updDate" timestamp(0) NOT NULL DEFAULT now(),
  "updUsr" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  CONSTRAINT "olbia_elenco_prezzi_layers_pkey" PRIMARY KEY ("idprezzo", "laygidd", "layname"));

- [x] Postgres soffre di connessioni puoi controllare e fargli manutenzione?

Layer Pozzetto 

- [x] posa_inf_esistente	bool	
- [x] posa_interrato_aff	bool

- [ ] SU TUTTI  LAYER EDITABILI AGGIUNGERE UN CAMPO BOOL "edit_closed"  --> editing terminato

**Comment by Verticalsrl** [comment]
@armagaet  ho aggiunto dei campi sotto tratta

**Comment by armagaet** [comment]
aggiunti i campi anche ai layer sotto lo schema pni_aib_template

creata la tabella per ogni schema e aggiunt allo schema template:
CREATE TABLE pni_aib_template.elenco_prezzi_layer
(
  idprezzo integer NOT NULL,
  laygidd integer NOT NULL,
  layname character varying(200) NOT NULL,
  "insDate" timestamp without time zone NOT NULL DEFAULT now(),
  "updDate" timestamp without time zone NOT NULL DEFAULT now(),
  "updUsr" character varying(100) NOT NULL,
  CONSTRAINT elenco_prezzi_layer_pkey PRIMARY KEY (idprezzo, laygidd, layname)
)

**Comment by Verticalsrl** [comment]
Guida performance
https://info.crunchydata.com/blog/optimize-postgresql-server-performance?hs_amp=true&__twitter_impression=true

**Comment by Verticalsrl** [comment]
@armagaet  scusa sulla tabella user_log degli schema ho dimenticato il campo "url" var 500
chiedo venia..

**Comment by Verticalsrl** [comment]
ho fatto un aggiornamento alla chek list altrimenti te le perdi

**Comment by armagaet** [comment]
query per aggiornare la tabella roma_elenco_prezzi in base alla tabella rma_elenco_prezzi_layer:
UPDATE roma_elenco_prezzi a SET prezzo = b.prezzo
FROM roma_elenco_prezzi_update as b WHERE a.art = b.art;

**Comment by armagaet** [comment]
> 
> 
> Guida performance
> https://info.crunchydata.com/blog/optimize-postgresql-server-performance?hs_amp=true&__twitter_impression=true

Configurazione in "/etc/postgresql/9.6/main/postgresql.conf" al 15/05/2020 (come si vede avevo già modificato i parametri di base per implementare il sistema):
#tune up postgresql - riccardo
shared_buffers = 512MB
temp_buffers = 16MB
work_mem = 128MB
maintenance_work_mem = 256MB
max_stack_depth = 6MB
effective_cache_size = 512MB


Valori consigliati presi dalla guida di cui l'url sopra:
#tune up postgresql - riccardo - 15/05/2020
shared_buffers = 1024MB
temp_buffers = 16MB
work_mem = 128MB
maintenance_work_mem = 256MB
max_stack_depth = 6MB
effective_cache_size = 2048MB

**Comment by Verticalsrl** [comment]
@armagaet  ho generato uno schema con l'ultimo plug e non mi ha metto il campo url --> cher 500  su user_log puoi verificare?

**Comment by armagaet** [comment]
> 
> 
> @armagaet ho generato uno schema con l'ultimo plug e non mi ha metto il campo url --> cher 500 su user_log puoi verificare?

@Verticalsrl  si era persa questa modifica esattamete quando abbiamo fatto quel push/commit incrociato...
L'ho ristabilita, e ripushato il tutto

**Comment by Verticalsrl** [comment]
@armagaet un po' di attività, abbiamo stravolto un po' la struttura ti tratta e pozzetti sostanzialmente si è deciso di lasciare i dati di progetto invariati e lavorare su nuovi campi su cui poi si interverrà per la parte di prezzi.
**LAYER TRATTA**
- [x] minitubi_j	json	0	0	-1	
- [x] cavi_j	json	0	0	-1
- [x] ripr_tipo	varchar	255	
- [x] ripr_larghezza	float4	
- [x] ripr_contestuale	bool	0
**- [ ] ripr_cls	bool	0	0**
- [x] ripr_rete_elettro	bool
- [x] ripr_geogriglia	bool				
- [x] ripr_scarifica	bool	
**- [ ] riempimento_cls	bool**
Attenzione che i campi in grassetto già ci sono gli ho solo ordinati in tabella

**LAYER POZZETTI**
- [x] passacavi	int4	32
- [x] num_tubi	varchar	100	
- [x] diam_tubo	varchar	100	
- [x] lunghezza_tubo	float8	
- [x] autoestinguente	bool	0	

**TABELLA MAPPA VALORI**
questa tabella è cambiata un po'  "tipo Progetto" prevede tre valori null per progetti AB e CD , cd solo per i progetti CD e AB idem.
Nel campo "condizionali" scrivo man mano come si comportano i valori, è stato fatto un errore in principio quello di non suddividere i valori dalle descrizioni così adesso ogni volta che Gatti mi cambia un descrizione rischiamo di incasinare le regole, ora vediamo se porre rimedio o lasciare così

**Comment by Verticalsrl** [comment]
- [ ] Creare sotto ogni schema AB e CD  la tabella "tab_nodo_ottico" di seguito l'sql

CREATE TABLE "olbia_ss03_03w1"."tab_nodo_ottico" (
  "gidd" int2 NOT NULL DEFAULT nextval('"olbia_ss03_03w1"."noto-ottico_gidd_seq"'::regclass),
  "posa" bool,
  "giunzione" bool,
  "collaudo" bool,
  "tipo_posa" varchar(255) COLLATE "pg_catalog"."default",
  "staffato" bool,
  "passacavi" bool,
  "gidd_pozzetto" int4,
  "tipo" varchar(255) COLLATE "pg_catalog"."default",
  "attestazione" json,
  "splitter_nc" json,
  CONSTRAINT "noto-ottico_pkey" PRIMARY KEY ("gidd")
)
;

ALTER TABLE "olbia_ss03_03w1"."tab_nodo_ottico" 
  OWNER TO "postgres";

COMMENT ON COLUMN "olbia_ss03_03w1"."tab_nodo_ottico"."attestazione" IS 'campo contentete ncavi x attestazione x scorta';

COMMENT ON COLUMN "olbia_ss03_03w1"."tab_nodo_ottico"."splitter_nc" IS 'contiene qta splitter e tipo';

**Comment by Verticalsrl** [comment]
Al Termine della generazione di ogni schema AB e CD (verificare che ci siano gli stessi campi) lanciare queste due query di consolidamento sul TRATTA (serve per popolare i campi  json con i dati di progetto)

- [ ] **minitubi j**

update underground_route
set minitubi_j = cast(jsonelupd as json)
from
(
select gidd,concat('[' , STRING_AGG(jsonelupdriga,','),']') jsonelupd from
(
select gruppo,gidd,concat('{"tipologia":"",',STRING_AGG(elemjson,',' order by riga DESC),',"posato":false , "calzamultic" : false}') jsonelupdriga from
(
select ( (row_number() over () / 2) + mod( row_number() over (),2)) as gruppo,(row_number() over ()) as riga,gidd,elem,case when mod( row_number() over (),2) = 0 then concat('"tipo":','"',elem ,'"') else concat('"num":','"',elem ,'"') end as elemjson from
(
select gidd , UPPER(unnest(string_to_array(tipo_mtubi, ' '))) as "elem" from underground_route where tipo_mtubi is not null and minitubi_j is null
order by gidd
) x
) h group by gidd,gruppo order by gidd
) hh
group by gidd
) jsontbl
where underground_route.gidd = jsontbl.gidd and minitubi_j is null


----------------------------------------------------------------------

- [ ] **cavi j**

update underground_route
set cavi_j = cast(jsonelupd as json)
from
(
select gidd,concat('[' , STRING_AGG(jsonelupdriga,','),']') jsonelupd from
(
select gruppo,gidd,concat('{"tipologia":"",',STRING_AGG(elemjson,',' order by riga),',"posab":false , "posam" : false}') jsonelupdriga from
(
select ( (row_number() over () / 2) + mod( row_number() over (),2)) as gruppo,(row_number() over ()) as riga,gidd,elem,case when mod( row_number() over (),2) = 0 then concat('"numfibre":','"',elem ,'"') else concat('"numcavi":','"',elem ,'"') end as elemjson from
(
select gidd , UPPER(unnest(string_to_array(num_fibre, ' '))) as "elem" from underground_route where num_fibre is not null and cavi_j is null order by gidd
) x
) h group by gidd,gruppo order by gidd
) hh
group by gidd
) jsontbl
where underground_route.gidd = jsontbl.gidd and cavi_j is null

**Comment by armagaet** [comment]
messo in issues a parte gli ultimi sviluppi da fare.
questa issue la chiudo
