### ISSUE TITLE
Modifiche dell'operatore da riportare su PNI: come facilitare l'aggiornamento

### ISSUE THREAD

**Issue by armagaet** [Verticalsrl/progettoPNI_2#4]
volevamo implementare delle funzioni per rendere più visibili a voi le modifiche "di ritorno" apportate dall'operatore in cantiere: avete degli shp di esempio "prima" e "dopo" esser passati tra le mani dell'operatore in cantiere? in modo da far risaltare al meglio su QGis le modifiche e semplificare a voi le successive operazioni di aggiornamento manuale dei dati sulla piattaforma PNI...

**Comment by armagaet** [comment]
per le modifiche in cantiere l’operatore deve solo modificare la colonna “constructi” e mettere “realizzato” e compilare le colonne che servono, da qui abbiamo evidenza che la tratta può essere inserita in PNI, a tal proposito può essere utile aggiungere agli shp che vengono caricati una colonna “inserito in PNI”, da compilare una volta inserito il dato , così da poter filtrare gli elementi realizzati ma non inseriti.

@nicola.guglielmi@sinergica.pro

**Comment by armagaet** [comment]
Attendo maggiori specifiche ed eventualmente un esempio di progetto (shapefile) "prima" e "dopo" il passaggio in cantiere

**Comment by Verticalsrl** [comment]
questa segnalazione è piuttosto vecchia la chiudo
