### ISSUE TITLE
Migliorie versione 2.2

### ISSUE THREAD

**Issue by nicoladontpanic** [Verticalsrl/progettoPNI_2#6]
Provando la versione 2.2 abbiamo riscontrato alcune cose (A&B)
- Tratta: se ebw_propri diverso da EOF anche surface_ma non deve essere visualizzato (come ebw_tipo)
- Manca ZERO su numero minitubi
- Tratta: se mettiamo proprietario EOF non salva la tipologia e di conseguenza non lo visualizziamo
- il campo num_cavi deve essere numerico
- abbiamo aggiornato il campo diam_mtubi e num_mtubi (v. googledrive)
-abbiamo notato che i pozzetti vengono visualizzati in maniera errata rispetto alla legenda del progetto che vi avevamo mandato
-il gruppo di layer "OTTICO" deve andare sotto tutti i layer del gruppo "PROGETTO CIVILE", non dentro il gruppo

**Comment by AndreaSINERGICA** [comment]
Aggiungo che nel layer mit_bay (PTE) si è persa la query "tipo_posa" = 'F'

**Comment by Verticalsrl** [comment]
mi pare abbiate imparato a mettere gli issues :p
bene vediamo se è più semplice da gestire

**Comment by armagaet** [comment]
**1)** _il campo **num_cavi** deve essere numerico_
Nello shapefile di provenienza dal PNI il campo "num_cavi" NON è numerico ma è di tipo testo. Di conseguenza, è possibile ritrovarsi dei contenuti di tipo testuale all'interno di questo campo (ad esempio nel caso di Grosseto ho ritrovato la stringa "num_cavi" all'interno del campo "num_cavi"). Potrebbero dunque esserci delle complicazioni a convertire questo campo in intero al momento dell'importazione dello shp su DB.
Una soluzione potrebbe essere quella di creare un ALTRO CAMPO questo sì veramente di tipo integer sul quale riversare il contenuto del campo num_cavi, ECCETTO quei contenuti di tipo stringa NON convertibili in integer. Si perderebbero delle informazioni, e si aggiungono delle complicazioni, da valutare. Quale problema specifico riscontrate nell'avere tale campo come testo (versione originale da PNI) piuttosto che numerico

**Comment by armagaet** [comment]
**2)** _Tratta: se mettiamo proprietario EOF non salva la tipologia e di conseguenza non lo visualizziamo_
La regola impostata è che la tipologia (campo ebw_tipo_p) viene visualizzata proprio se ebw_propr='EOF'. Avete riscontrato qualche baco in questa regola? A me risulta correttamente applicata.
O volete modificarla?

**Comment by armagaet** [comment]
**3)** _Tratta: se ebw_propri diverso da EOF anche surface_ma non deve essere visualizzato (come ebw_tipo)_
Risolto. Nella prossima versione del plugin vedrete il campo "surface_ma" solo se ebw_propr='EOF'

**Comment by armagaet** [comment]
**4)** _abbiamo aggiornato il campo diam_mtubi e num_mtubi (v. googledrive)
-abbiamo notato che i pozzetti vengono visualizzati in maniera errata rispetto alla legenda del progetto che vi avevamo mandato
-il gruppo di layer "OTTICO" deve andare sotto tutti i layer del gruppo "PROGETTO CIVILE", non dentro il gruppo_
Ho preso come ultimo riferimento il vostro progetto "_PC06e_REAL_CHECK.qgz".
Ho aggiornato la visualizzazione dei pozzetti in base al progetto di riferimento.
In merito al gruppo OTTICO, lo avevo inserito dentro al gruppo "PROGETTO CIVILE" in seguito ad un'altra vostra mail. Devo metterlo FUORI dal gruppo "PROGETTO CIVILE", sopra di esso (come nel progetto di riferimento) o sotto di esso?
Allego immagine della legenda del progetto di riferimento "_PC06e_REAL_CHECK.qgz".
![image](https://user-images.githubusercontent.com/19342770/72717069-a2649500-3b73-11ea-9d19-625446c63271.png)

**Comment by armagaet** [comment]
**4bis)** _abbiamo aggiornato il campo diam_mtubi e num_mtubi (v. googledrive)_
Scusate su quale layer? Tratta? In che senso lo avete aggiornato, avete aggiunto altre opzioni?

**Comment by armagaet** [comment]
**5)** > Aggiungo che nel layer mit_bay (PTE) si è persa la query "tipo_posa" = 'F'
Questa non l'ho capita. Il campo tipo_posa deve essere inserito nel form di editing? Che valori può assumere? Oppure la regola deve essere che ad ogni NUOVO inserimento questo campo deve valere 'F'? Ma poi può venir modificato, appunto inserendolo nel form di editing?

**Comment by nicoladontpanic** [comment]
> **1)** _il campo **num_cavi** deve essere numerico_
> Nello shapefile di provenienza dal PNI il campo "num_cavi" NON è numerico ma è di tipo testo. Di conseguenza, è possibile ritrovarsi dei contenuti di tipo testuale all'interno di questo campo (ad esempio nel caso di Grosseto ho ritrovato la stringa "num_cavi" all'interno del campo "num_cavi"). Potrebbero dunque esserci delle complicazioni a convertire questo campo in intero al momento dell'importazione dello shp su DB.
> Una soluzione potrebbe essere quella di creare un ALTRO CAMPO questo sì veramente di tipo integer sul quale riversare il contenuto del campo num_cavi, ECCETTO quei contenuti di tipo stringa NON convertibili in integer. Si perderebbero delle informazioni, e si aggiungono delle complicazioni, da valutare. Quale problema specifico riscontrate nell'avere tale campo come testo (versione originale da PNI) piuttosto che numerico

Nell'inserimento dei valori i numeri non sono in ordine crescente, non è necessario avere un campo numerico ma un ordine crescente delle opzioni

**Comment by nicoladontpanic** [comment]
> **5)** > Aggiungo che nel layer mit_bay (PTE) si è persa la query "tipo_posa" = 'F'
> Questa non l'ho capita. Il campo tipo_posa deve essere inserito nel form di editing? Che valori può assumere? Oppure la regola deve essere che ad ogni NUOVO inserimento questo campo deve valere 'F'? Ma poi può venir modificato, appunto inserendolo nel form di editing?

Nel progetto caricato devono essere visualizzati solo i PTE che hanno il campo "tipo_posa" = F, in caso di nuovi inserimenti il campo "tipo_posa" deve essere automaticamente compilato come "F"

**Comment by nicoladontpanic** [comment]
> **4)** _abbiamo aggiornato il campo diam_mtubi e num_mtubi (v. googledrive) -abbiamo notato che i pozzetti vengono visualizzati in maniera errata rispetto alla legenda del progetto che vi avevamo mandato -il gruppo di layer "OTTICO" deve andare sotto tutti i layer del gruppo "PROGETTO CIVILE", non dentro il gruppo_
> Ho preso come ultimo riferimento il vostro progetto "_PC06e_REAL_CHECK.qgz".
> Ho aggiornato la visualizzazione dei pozzetti in base al progetto di riferimento.
> In merito al gruppo OTTICO, lo avevo inserito dentro al gruppo "PROGETTO CIVILE" in seguito ad un'altra vostra mail. Devo metterlo FUORI dal gruppo "PROGETTO CIVILE", sopra di esso (come nel progetto di riferimento) o sotto di esso?
> Allego immagine della legenda del progetto di riferimento "_PC06e_REAL_CHECK.qgz".
> ![image](https://user-images.githubusercontent.com/19342770/72717069-a2649500-3b73-11ea-9d19-625446c63271.png)

Abbiamo aggiornato il file di GDrive, Form_Tratte, Form_Pozzetti e Form_Tratte_Aeree hanno subito modifiche, per essere allineate il più possibile al listino prezzi.
Ti alleghiamo il nuovo file qgz  per avere gli stili grafici di riferimento e la posizione dei vari gruppi di layer.
[_PC06e_20200121.zip](https://github.com/Verticalsrl/progettoPNI_2/files/4091778/_PC06e_20200121.zip)

**Comment by armagaet** [comment]
> > **1)** _il campo **num_cavi** deve essere numerico_
> > Nello shapefile di provenienza dal PNI il campo "num_cavi" NON è numerico ma è di tipo testo. Di conseguenza, è possibile ritrovarsi dei contenuti di tipo testuale all'interno di questo campo (ad esempio nel caso di Grosseto ho ritrovato la stringa "num_cavi" all'interno del campo "num_cavi"). Potrebbero dunque esserci delle complicazioni a convertire questo campo in intero al momento dell'importazione dello shp su DB.
> > Una soluzione potrebbe essere quella di creare un ALTRO CAMPO questo sì veramente di tipo integer sul quale riversare il contenuto del campo num_cavi, ECCETTO quei contenuti di tipo stringa NON convertibili in integer. Si perderebbero delle informazioni, e si aggiungono delle complicazioni, da valutare. Quale problema specifico riscontrate nell'avere tale campo come testo (versione originale da PNI) piuttosto che numerico
> 
> Nell'inserimento dei valori i numeri non sono in ordine crescente, non è necessario avere un campo numerico ma un ordine crescente delle opzioni

ok nella prossima versione che rilascerò i numeri verranno scritti come "01, 02, etc" in modo tale che siano ordinati.

**Comment by AndreaSINERGICA** [comment]
> > > **1)** _il campo **num_cavi** deve essere numerico_
> > > Nello shapefile di provenienza dal PNI il campo "num_cavi" NON è numerico ma è di tipo testo. Di conseguenza, è possibile ritrovarsi dei contenuti di tipo testuale all'interno di questo campo (ad esempio nel caso di Grosseto ho ritrovato la stringa "num_cavi" all'interno del campo "num_cavi"). Potrebbero dunque esserci delle complicazioni a convertire questo campo in intero al momento dell'importazione dello shp su DB.
> > > Una soluzione potrebbe essere quella di creare un ALTRO CAMPO questo sì veramente di tipo integer sul quale riversare il contenuto del campo num_cavi, ECCETTO quei contenuti di tipo stringa NON convertibili in integer. Si perderebbero delle informazioni, e si aggiungono delle complicazioni, da valutare. Quale problema specifico riscontrate nell'avere tale campo come testo (versione originale da PNI) piuttosto che numerico
> > 
> > 
> > Nell'inserimento dei valori i numeri non sono in ordine crescente, non è necessario avere un campo numerico ma un ordine crescente delle opzioni
> 
> ok nella prossima versione che rilascerò i numeri verranno scritti come "01, 02, etc" in modo tale che siano ordinati.

perfetto.

**Comment by armagaet** [comment]
dovrebbe essersi tutto risolto con la versione 2.4
