### ISSUE TITLE
**2)** _Tratta: se mettiamo proprietario EOF non salva la tipologia e di conseguenza non lo visualizziamo_

### ISSUE THREAD

**Issue by nicoladontpanic** [Verticalsrl/progettoPNI_2#8]
Sulle nuove tratte inserite non salva la tipologia e di conseguenza anche se la tratta è salvata non viene visualizzata, per poterla visualizzare dobbiamo accendere il campo delle tratte complessivo (tratte nere) e a quel punto ci accorgiamo che non è salvata nessuna tratta.

**Comment by armagaet** [comment]
prossima versione 2.4 dovrei aver risolto questo baco.
Di default il valore sarà 'Trincea' per tutti quei proprietari diversi da EOF, quindi non dovrebbe più presentarsi il problema di non vedere le tracce appena disegnate.
