### ISSUE TITLE
Plugin v2.6: richiesta aggiornamento 

### ISSUE THREAD

**Issue by AndreaSINERGICA** [Verticalsrl/progettoPNI_2#9]
Ciao Riccardo, ti elenchiamo una serie di richieste per l’aggiornamento del plugin:

1)	Per gli shp tratta, tratta_aerea, pozzetti, colonnine, giunti e mit_bay deve essere aggiunta una TAB zero nella finestra di inserimento **0_DITTA** (campi: società, subappalto, riferimento).
Il senso di questa finestra è che l’assistente di cantiere quando dovrà inserire i dati si potrebbe ritrovare un caso del genere:  
•	il subappalto 1 realizza 2 pozzetti, 
•	il subappalto 2 realizza la tratta che li collega, 
•	il subappalto 3 realizza 2 giunti nei 2 pozzetti, 
•	il subappalto 4 realizza i cavi nella tratta, 
•	il subappalto 5 realizza le giunzioni dei cavi.

2) TRATTA
2.1) TAB 1_TRATTA: in caso di proprietario EOF il campo tipologia materiale deve essere compilato obbligatoriamente e quindi diventare vincolante alla chiusura con OK della maschera d’inserimento.
2.2) TAB 1_TRATTA: in caso di proprietario EOF e Tipologia Minitrincea o Microtrincea il campo tipologia materiale non deve essere visibile, ma sul database deve essere inserito in automatico Asfalto.
2.3) TAB 1_TRATTA: aggiungere caselle di spunta Maggiore disfacimento, Adduzione e Attraversamento (come scavo a mano).
2.4) TAB 2_SOTTOEQUIPAGGIAMENTO: aggiungere campo _lunghezza Tubo_.
2.5) TAB 2_SOTTOEQUIPAGGIAMENTO: il campo tipologia minitubi non è aggiornato secondo le ultime indicazioni in Google Drive.
2.6) TAB 2_SOTTOEQUIPAGGIAMENTO: i valori di numero minitubi deve essere crescente (come fatto per il campo cavi inseriti (00, 01, ecc).

3) TRATTA AEREA
3.1) in caso di proprietario EOF deve attivarsi una nuova casella nuova tesata. Se non viene spuntata non deve essere attivo il bottone OK.
3.2) in caso di proprietario diverso da EOF deve attivarsi una nuova casella fascettato. Se non viene spuntata non deve essere attivo il bottone OK.

4) COLONNINE
aggiunta campi: 
•	campo numerico _giunzioni_
•	campo numerico _cavi_attestati_

Grazie

**Comment by armagaet** [comment]
Ciao Nicola ti rispondo punto per punto:
1) devo parlarne con Andrea, probabilmente questa parte si svilupperà solo sulla parte web

2.1) verrà implementata sulla parte web
2.2) ok. la correzione del valore avverrà poi tramite controllo sul DB
2.3) mi sembra di capire che, come "scavo a mano", bisognerebbe aggiungere i 3 campi: disfacimento, Adduzione e Attraversamento. Ognuno di questi potrebbe essere spuntato. O sono mutualmente esclusivi?
2.4) il campo lunghezza Tubo esiste già sulla tabella delle tratte oppure deve essere creato ad hoc?
2.5) il campo "tipologia minitubi" (diam_minit) è un campo che può avere molteplici valori. Come si era detto, la compilazione di questo campo, come di altri simili, verrà implementata nella parte web.
Se è utile avere la possibilità di compilare questi campi anche tramite i form di QGis, allora in questo caso li potremmo lasciare come campo di testo libero in modo tale che l'operatore in grado di usare QGis possa inserire questi dati in maniera autonoma
2.6) ok

3) scusami in entrambi questi 2 casi non si può far eseguire questa operazione direttamente dal DB? Cioè se l'utente sceglie EOF impongo lato DB (dunque in modo trasparente all'operatore) che sia una "nuova tesata". E così via.
Tra l'altro, serve salvare quest'informazione in un nuovo campo? Cioè poi voi, per ricaricare i dati sul sistema PNI, come vi serve avere quest'informazione in modo che sia fruibile?

4) solo una precisazione: i campi numerici sono di tipo integer o double precision? Per ottimizzare le risorse del DB...

**Comment by armagaet** [comment]
ciao avete novità in merito?

**Comment by AndreaSINERGICA** [comment]
> Ciao Nicola ti rispondo punto per punto:
> 
> 1. devo parlarne con Andrea, probabilmente questa parte si svilupperà solo sulla parte web
> 
> 2.1) verrà implementata sulla parte web OK 
> 2.2) ok. la correzione del valore avverrà poi tramite controllo sul DB OK
> 2.3) mi sembra di capire che, come "scavo a mano", bisognerebbe aggiungere i 3 campi: disfacimento, Adduzione e Attraversamento. Ognuno di questi potrebbe essere spuntato. O sono mutualmente esclusivi? POTREBBERO ESSERE SPUNTATI
> 2.4) il campo lunghezza Tubo esiste già sulla tabella delle tratte oppure deve essere creato ad hoc? VA CREATO
> 2.5) il campo "tipologia minitubi" (diam_minit) è un campo che può avere molteplici valori. Come si era detto, la compilazione di questo campo, come di altri simili, verrà implementata nella parte web. OK
> Se è utile avere la possibilità di compilare questi campi anche tramite i form di QGis, allora in questo caso li potremmo lasciare come campo di testo libero in modo tale che l'operatore in grado di usare QGis possa inserire questi dati in maniera autonoma
> 2.6) ok
> 
> 3. scusami in entrambi questi 2 casi non si può far eseguire questa operazione direttamente dal DB? Cioè se l'utente sceglie EOF impongo lato DB (dunque in modo trasparente all'operatore) che sia una "nuova tesata". E così via. OK
>    Tra l'altro, serve salvare quest'informazione in un nuovo campo? Cioè poi voi, per ricaricare i dati sul sistema PNI, come vi serve avere quest'informazione in modo che sia fruibile? SERVE UN NUOVO CAMPO PERCHè POI L'OPERATORE DEVE CARICARLO IN PNI
> 4. solo una precisazione: i campi numerici sono di tipo integer o double precision? Per ottimizzare le risorse del DB... INTENGER

**Comment by armagaet** [comment]
> 2.2) TAB 1_TRATTA: in caso di proprietario EOF e Tipologia Minitrincea o Microtrincea il campo tipologia materiale non deve essere visibile, ma sul database deve essere inserito in automatico Asfalto.

Messa la condizione su "surface_ma" campo che aveva come alias "tipologia materiale".
Ora vedo sul foglio gdrive che l'alias è "superficie scavo": qual'è l'alias corretto?

**Comment by armagaet** [comment]
Ho aggiornato il file su gdrive PluginQGis.
Ho aggiornato il plug e il progetto QGis e relative form di edit.
A breve seguirà un nuovo rilascio
